---
kind: pipeline
name: opencti-tests

steps:
- name: api-tests
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  environment:
    APP__ADMIN__PASSWORD: admin
    APP__SYNC_RAW_START_REMOTE_URI: http://opencti-raw-start:4100/graphql
    APP__SYNC_LIVE_START_REMOTE_URI: http://opencti-live-start:4200/graphql
    APP__SYNC_DIRECT_START_REMOTE_URI: http://opencti-direct-start:4300/graphql
    APP__SYNC_RESTORE_START_REMOTE_URI: http://opencti-restore-start:4400/graphql
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    REDIS__HOSTNAME: redis
    ELASTICSEARCH__URL: http://elastic:9200
    MINIO__ENDPOINT: minio
    RABBITMQ__HOSTNAME: rabbitmq
    SUBSCRIPTION_SCHEDULER__ENABLED: false
    SMTP__HOSTNAME: smtp.ethereal.email
    SMTP__PORT: 587
    SMTP__USERNAME: jennyfer.mraz@ethereal.email
    SMTP__PASSWORD: frhJ2mSPTfaEutpbug
  commands:
  - lscpu
...
